### ISSUE TITLE
management of ontologies

### ISSUE THREAD

**Issue by chenzhenhui** [cbib/XEML-Lab#11]
Hi,

This afternoon we could not select in the ontologies a child of a header in xeo . for example watering in water

**Comment by ebouilhol** [comment]
Do you mean that you can't drag and drop a term of the xeo ontologie in a story like this ?

![capture du 2015-03-10 15 14 20](https://cloud.githubusercontent.com/assets/4415638/6576582/7e1ca05c-c738-11e4-89c8-7d80e6cef500.png)

Here I can do it, so if you can add here an image of where your problem is, it will be very helpfull !

Thanks a lot,

Emmanuel

**Comment by chenzhenhui** [comment]
Hi, 
We can do it now.
Merci beaucoup.

Chen

**Comment by ebouilhol** [comment]
That's great, thanks, I lock this thread !
